#!/usr/bin/env bash
# Generated by tools/agents/sync.py; edit tools/agents instead.
ROOT="$(cd "$(dirname "$0")/../.." && pwd)" || exit 2
if ! python3 "$ROOT/tools/agents/adapter.py" --runtime claude; then
  # Claude treats most other nonzero exits as advisory failures.
  echo 'Workspace policy adapter unavailable; action blocked.' >&2
  exit 2
fi
