#!/usr/bin/env python3
"""Generated by tools/agents/sync.py; edit tools/agents instead."""
import json
import importlib.util
from pathlib import Path

try:
    root = Path(__file__).resolve().parents[2]
    spec = importlib.util.spec_from_file_location("qa_policy_adapter", root / "tools/agents/adapter.py")
    adapter = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(adapter)
    adapter.main(runtime="codex", root=root)
except Exception:
    print(json.dumps({"hookSpecificOutput": {"hookEventName": "PreToolUse",
          "permissionDecision": "deny", "permissionDecisionReason": "Workspace policy adapter unavailable"}}))
