#!/usr/bin/env python3
"""Generate tickets/INDEX.md from ticket frontmatter.

    python3 tools/tickets/index.py           # rewrite tickets/INDEX.md
    python3 tools/tickets/index.py --check   # exit 1 if INDEX.md is stale (CI)
"""
from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from validate import TICKETS, frontmatter  # noqa: E402

INDEX = TICKETS / "INDEX.md"
HEADER = (
    "# Tickets\n\n"
    "Generated by `tools/tickets/index.py` — do not edit by hand. One row per\n"
    "ticket file; the frontmatter is the source.\n\n"
    "| ID | Title | Scope | Status | Verdict | Updated | Next action |\n"
    "|---|---|---|---|---|---|---|\n"
)


def render() -> str:
    rows = []
    for p in sorted(TICKETS.glob("*.md")):
        if p.name.startswith("_") or p.name == "INDEX.md":
            continue
        fm = frontmatter(p.read_text(encoding="utf-8")) or {}
        rows.append(
            "| [{id}]({file}) | {title} | {scope} | {status} | {verdict} | {updated} | {next} |".format(
                id=fm.get("id", p.stem), file=p.name, title=fm.get("title", ""),
                scope=fm.get("scope", ""), status=fm.get("status", ""),
                verdict=fm.get("verdict", ""), updated=fm.get("updated", ""),
                next=fm.get("next_action", "").strip('"'),
            )
        )
    rows.sort(key=lambda r: r.split("|")[6].strip(), reverse=True)
    return HEADER + "\n".join(rows) + ("\n" if rows else "")


def main(argv: list[str]) -> int:
    content = render()
    if "--check" in argv:
        current = INDEX.read_text(encoding="utf-8") if INDEX.exists() else ""
        if current != content:
            print("tickets/INDEX.md is stale — run python3 tools/tickets/index.py")
            return 1
        print("tickets/INDEX.md is current")
        return 0
    INDEX.write_text(content, encoding="utf-8")
    print(f"wrote {INDEX.relative_to(TICKETS.parent)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
