#!/usr/bin/env python3
"""Generate project runtime adapters from .cursor sources (Python 3.11+)."""
import argparse
import hashlib
import json
import os
from pathlib import Path
import re
import sys
import tempfile
import tomllib


ROOT = Path(__file__).resolve().parents[2]
LEDGER = "tools/agents/generated.json"
OLD_LEDGER = ".codex/agent-core-managed.json"
CONFIGS = {"codex": ".codex/hooks.json", "claude": ".claude/settings.json"}
MATCHER = "^(Bash|exec_command|Read|Edit|Write|MultiEdit|NotebookEdit|apply_patch|mcp__.*)$"


class SyncError(Exception):
    pass


def digest(data):
    return hashlib.sha256(data).hexdigest()


def encoded(value):
    return (json.dumps(value, indent=2, ensure_ascii=False) + "\n").encode()


def read_json(path):
    value = json.loads(path.read_text())
    if not isinstance(value, dict):
        raise SyncError(f"Expected JSON object: {path}")
    return value


def metadata(path):
    text = path.read_text()
    parts = text.split("---", 2)
    if len(parts) != 3 or parts[0].strip():
        raise SyncError(f"Missing frontmatter: {path}")
    fields = {}
    for line in parts[1].strip().splitlines():
        if not line or line.startswith("#"):
            continue
        if line[:1].isspace() or ":" not in line:
            raise SyncError(f"Use single-line scalar frontmatter in {path}")
        key, value = line.split(":", 1)
        value = value.strip()
        if value.startswith('"'):
            value = json.loads(value)
        elif value.startswith("'") and value.endswith("'"):
            value = value[1:-1].replace("''", "'")
        if not value or value in {"|", ">"}:
            raise SyncError(f"Missing or unsupported {key} in {path}")
        fields[key] = value
    for key in ("name", "description"):
        if not fields.get(key):
            raise SyncError(f"Missing {key}: {path}")
    if not re.fullmatch(r"[a-z0-9][a-z0-9-]*", fields["name"]):
        raise SyncError(f"Invalid agent/skill name: {path}")
    return fields, parts[2].lstrip()


def hook_groups(runtime):
    if runtime == "codex":
        command = 'python3 "$(git rev-parse --show-toplevel)/.codex/hooks/adapter.py"'
    else:
        command = 'bash "$CLAUDE_PROJECT_DIR/.claude/hooks/pretooluse.sh"'
    groups = {}
    for event in ("PreToolUse", "SessionStart", "Stop", "SessionEnd"):
        group = {"hooks": [{"type": "command", "command": command,
                             "timeout": 3 if event == "SessionEnd" else 30}]}
        if event == "PreToolUse":
            group = {"matcher": MATCHER, **group}
        groups[event] = [group]
    return groups


def desired_files(root):
    files = {
        ".codex/hooks/adapter.py": (root / "tools/agents/templates/codex-adapter.py").read_bytes(),
        ".claude/hooks/pretooluse.sh": (root / "tools/agents/templates/claude-pretooluse.sh").read_bytes(),
    }
    modes = {".claude/hooks/pretooluse.sh": 0o755}
    for path in sorted((root / ".cursor/agents").glob("*.md")):
        fields, body = metadata(path)
        name = fields["name"]
        if name != path.stem:
            raise SyncError(f"Agent name must match filename: {path}")
        readonly = fields.get("readonly", "false")
        if readonly not in {"true", "false"}:
            raise SyncError(f"readonly must be true or false: {path}")
        codex = '# Generated by tools/agents/sync.py; edit .cursor/agents.\n'
        for key, value in (("name", name), ("description", fields["description"]),
                           ("developer_instructions", body)):
            codex += f"{key} = {json.dumps(value, ensure_ascii=False)}\n"
        if readonly == "true":
            codex += 'sandbox_mode = "read-only"\n'
        tomllib.loads(codex)
        files[f".codex/agents/{name}.toml"] = codex.encode()
        claude = "---\n" + "\n".join(f"{key}: {json.dumps(fields[key], ensure_ascii=False)}"
                                    for key in ("name", "description"))
        claude += "\nmodel: inherit\n"
        if readonly == "true":
            # A Write/Edit denylist still leaves shell, MCP, and delegation
            # paths able to mutate; these roles need only local source reads.
            claude += "tools: Read, Grep, Glob\n"
        claude += "---\n\n" + body
        files[f".claude/agents/{name}.md"] = claude.encode()
    skill_root = root / ".cursor/skills"
    for skill in sorted(skill_root.iterdir()):
        if not skill.is_dir() or skill.is_symlink():
            raise SyncError(f"Expected a real canonical skill directory: {skill}")
        fields, _ = metadata(skill / "SKILL.md")
        if fields["name"] != skill.name:
            raise SyncError(f"Skill name must match directory: {skill}")
        for path in sorted(skill.rglob("*")):
            if path.is_symlink():
                raise SyncError(f"Canonical skill must not contain symlinks: {path}")
            if path.is_file():
                relative = path.relative_to(skill_root).as_posix()
                for directory in (".agents/skills", ".claude/skills"):
                    target = f"{directory}/{relative}"
                    files[target] = path.read_bytes()
                    modes[target] = 0o755 if path.stat().st_mode & 0o111 else 0o644
    return files, {relative: modes.get(relative, 0o644) for relative in files}


def safe_path(root, relative, replacements=()):
    path = Path(relative)
    if path.is_absolute() or ".." in path.parts or str(path) == ".":
        raise SyncError(f"Invalid managed path: {relative}")
    for parent in (path, *path.parents):
        candidate = root / parent
        if candidate.is_symlink() and parent.as_posix() not in replacements:
            raise SyncError(f"Refusing generated path through a symlink: {parent}")
    return root / path


def merge_hooks(root, runtime, previous, wanted):
    path = root / CONFIGS[runtime]
    config = read_json(path) if path.exists() else {}
    hooks = config.setdefault("hooks", {})
    if not isinstance(hooks, dict):
        raise SyncError(f"Invalid hooks object: {path}")
    for event in sorted(set(previous) | set(wanted)):
        current = hooks.get(event, [])
        if not isinstance(current, list):
            raise SyncError(f"Invalid hook groups: {path}: {event}")
        current = current.copy()
        additions = list(wanted.get(event, []))
        for group in previous.get(event, []):
            if group not in current:
                raise SyncError(f"Managed hook changed locally: {path}: {event}; restore or move the custom hook first")
            index = current.index(group)
            current.pop(index)
            if additions:
                replacement = additions.pop(0)
                if replacement not in current:
                    current.insert(index, replacement)
        for group in additions:
            if group not in current:
                current.append(group)
        hooks[event] = current
    return encoded(config)


def load_state(root):
    path = safe_path(root, LEDGER)
    if path.exists():
        state = read_json(path)
        if state.get("version") != 1 or not isinstance(state.get("files"), dict) or not isinstance(state.get("hooks"), dict):
            raise SyncError("Invalid generated-file ledger")
        return state, False
    legacy = read_json(root / "tools/agents/legacy.json")
    # Only known historical output is adopted; an untracked collision is never
    # assumed to be generated simply because it has a familiar filename.
    return legacy, True


def plan(root):
    files, modes = desired_files(root)
    state, migrating = load_state(root)
    replacements = []
    if migrating:
        for skill in sorted((root / ".cursor/skills").iterdir()):
            relative = f".agents/skills/{skill.name}"
            path = root / relative
            expected = f"../../.cursor/skills/{skill.name}"
            if path.is_symlink():
                if os.readlink(path) != expected:
                    raise SyncError(f"Unexpected skill symlink: {relative}")
                replacements.append(relative)
            elif path.is_file():
                if path.read_text().strip() != expected:
                    raise SyncError(f"Unexpected skill file: {relative}")
                replacements.append(relative)
    updates = {}
    for relative, content in files.items():
        path = safe_path(root, relative, replacements)
        if any(relative.startswith(item + "/") for item in replacements):
            updates[relative] = content
            continue
        if path.exists():
            if not path.is_file():
                raise SyncError(f"Generated file collides with directory: {relative}")
            old = path.read_bytes()
            old_mode = path.stat().st_mode & 0o777
            if old == content and old_mode == modes[relative]:
                continue
            if (digest(old) != state["files"].get(relative)
                    or old_mode != state.get("modes", {}).get(relative, old_mode)):
                raise SyncError(f"Generated file changed locally: {relative}; edit the canonical source or move the custom file")
        updates[relative] = content
    deletions = []
    for relative, previous_hash in state["files"].items():
        if relative in files:
            continue
        path = safe_path(root, relative)
        if path.exists():
            if not path.is_file() or digest(path.read_bytes()) != previous_hash:
                raise SyncError(f"Obsolete generated file changed locally: {relative}")
            deletions.append(relative)
    groups = {runtime: hook_groups(runtime) for runtime in CONFIGS}
    for runtime, relative in CONFIGS.items():
        path = safe_path(root, relative)
        previous = state["hooks"].get(runtime, {})
        if migrating and not path.exists():
            previous = {}
        elif migrating and not (root / OLD_LEDGER).exists():
            present = read_json(path).get("hooks", {})
            if not isinstance(present, dict):
                raise SyncError(f"Invalid hooks object: {path}")
            adopted = {}
            for event, entries in present.items():
                if not isinstance(entries, list):
                    raise SyncError(f"Invalid hook groups: {path}: {event}")
                known = previous.get(event, []) + groups[runtime].get(event, [])
                for entry in entries:
                    if entry in known:
                        adopted.setdefault(event, []).append(entry)
                    elif any(marker in json.dumps(entry) for marker in
                             (".codex/hooks/adapter.py", ".claude/hooks/pretooluse.sh")):
                        raise SyncError(f"Unrecognized existing workspace hook: {path}: {event}")
            previous = adopted
        content = merge_hooks(root, runtime, previous, groups[runtime])
        if not path.exists() or path.read_bytes() != content:
            updates[relative] = content
    if migrating and (root / OLD_LEDGER).exists():
        path = safe_path(root, OLD_LEDGER)
        if digest(path.read_bytes()) != state["old_ledger_hash"]:
            raise SyncError("Legacy generated-file ledger changed locally; cannot safely migrate")
        deletions.append(OLD_LEDGER)
    ledger = encoded({"version": 1, "files": {key: digest(value) for key, value in sorted(files.items())},
                      "modes": dict(sorted(modes.items())),
                      "hooks": groups})
    if not (root / LEDGER).exists() or (root / LEDGER).read_bytes() != ledger:
        updates[LEDGER] = ledger
    return updates, deletions, replacements, modes


def sync(root, check=False):
    updates, deletions, replacements, modes = plan(root)
    changed = sorted(set(updates) | set(deletions) | set(replacements))
    if check:
        if changed:
            raise SyncError("Generated runtime drift:\n" + "\n".join(changed))
        return []
    for relative in replacements + deletions:
        (root / relative).unlink()
    for relative, content in updates.items():
        path = root / relative
        path.parent.mkdir(parents=True, exist_ok=True)
        with tempfile.NamedTemporaryFile(dir=path.parent, delete=False) as handle:
            handle.write(content)
            temp = Path(handle.name)
        try:
            temp.chmod(modes.get(relative, path.stat().st_mode & 0o777 if path.exists() else 0o644))
            temp.replace(path)
        finally:
            temp.unlink(missing_ok=True)
    return changed


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="report drift without changing files")
    args = parser.parse_args()
    try:
        changed = sync(ROOT, args.check)
    except (SyncError, OSError, ValueError, KeyError, TypeError) as exc:
        print(f"Agent sync failed: {exc}", file=sys.stderr)
        return 1
    print(f"Agent adapters {'updated (' + str(len(changed)) + ' paths)' if changed else 'are current'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
